version: "3"

services:
    mysql:
        platform: linux/x86_64 # M1チップ対応のため追記
        image: mysql:5.7
        container_name: javaoop-mysql
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: task_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - ./docker/db/data:/var/lib/mysql
        ports:
            - 33306:3306
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
